version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-container
    tty: true
    volumes:
      - ./:/user/wwww
      - /user/wwww/node_modules/ # keep node_modules existed in container
    restart: always
    ports:
      - '3000:3000'